### ISSUE TITLE
ReportThrottler not configurable

### ISSUE THREAD

**Issue by Bartjuh4** [anlutro/laravel-4-smart-errors#22]
Hi,
I noticed that the ReportThrottler that is build in with the error handler is not configurable. Can you add the MAX_AGE_SECONDS constant to the config file?
Thanks!

**Comment by anlutro** [comment]
Hey, thanks for the suggestion! This is now available in 2.4.10 - add [this line](https://github.com/anlutro/laravel-4-smart-errors/blob/e27e82f804bf7622310da15354da3955a891aeb3/src/config/config.php#L48-L52) to your config file to configure it.

**Comment by Bartjuh4** [comment]
Hey, Thanks for the quick reply and realization of my request! Keep up the good work!
