### ISSUE TITLE
Seeing smart errors on 4.2

### ISSUE THREAD

**Issue by levitating** [anlutro/laravel-4-smart-errors#25]
I am having a strange error on Laravel 4.2 where I see the errors on this page :

https://github.com/anlutro/laravel-4-smart-errors/blob/master/src/views/generic.blade.php

Could you write a bit of documentation on which conditions exactly result in the display of that page? That would be very helpful.

**Comment by anlutro** [comment]
When you say that you see "the errors", what exactly do you mean? Do you see the exception that triggered the error handler, or is the error unrelated?

I should definitely work on the documentation on when the error page is being shown. Unless I'm forgetting something, the conditions are:

- [The app is not running in CLI](https://github.com/anlutro/laravel-4-smart-errors/blob/18d44d1fe60eeda3e38b50bee3d681da4decd17e/src/anlutro/L4SmartErrors/Responders/ExceptionResponder.php#L21-L35)
- [`Config::get('app.debug')` is `false`](https://github.com/anlutro/laravel-4-smart-errors/blob/18d44d1fe60eeda3e38b50bee3d681da4decd17e/src/anlutro/L4SmartErrors/Responders/ExceptionResponder.php#L45-L54)
- No other error handler added with `App::error` has returned a response

**Comment by levitating** [comment]
I am doing this : 

Route::get('/tester', function()
{
	// return Response::view('protected.admin.master.create');

	$users = User::all();
	return View::make('protected.user.show', ['users' => $users]);

});

And getting this EXACT page : 

----------------------------------------------------------------
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>smarterror::error.genericErrorTitle</title>
	<style>
		* {
			font-family: sans-serif;
			line-height: 1.4em;
		}
		
		body {
			background: #fcfcfc;
			-webkit-font-smoothing: antialiased;
			-moz-font-smoothing: antialiased;
			-ms-font-smoothing: antialiased;
			-o-font-smoothing: antialiased;
			font-smoothing: antialiased;
		}
		
		h1 {
			text-align: center;
			font-size: 3.5em;
		}
		
		.error-message {
			padding: 30px;
			background: #fff;
			color: black;
		}
		
		a {
			color: black;
		}
		
		@media  screen and (min-width: 800px) {
			h1 {
				margin-top: 75px;
			}
			.error-message {
				max-width: 700px;
				margin: 50px auto;
				border-radius: 10px;
				border: 1px solid #ddd;
			}
		}
	</style>
</head>
<body>

<h1>smarterror::error.genericErrorTitle</h1>

<section class="error-message">
	
	<p>smarterror::error.genericErrorParagraph1</p>
	<p>smarterror::error.genericErrorParagraph2</p>
	<p style="text-align:center;">
			<a href="/">smarterror::error.frontpageLinkTitle</a>
	</p>

</section>

</body>
</html>

--------------------------------------------------------------------------

There doesn't seem to be any indication on from where this page is being generated, thus I am asking in which conditions we could see this generic error page that has no debug details to retrace its origin.

**Comment by anlutro** [comment]
The most likely cause is that `app.debug` is set to false in the config. This can happen if your environment detection in `bootstrap/start.php` is wrong.

You should be able to check your logs (`app/storage/logs/apache2handler.log` by default) and find the original exception there.

**Comment by levitating** [comment]
Ah that was it! Thank you.

A suggestion might be to display a clearer message when this happens, such as "Smart Errors, please turn on debug mode to see details."

**Comment by anlutro** [comment]
The problem with that is it would also show up to your end users when you deploy to production. I think it has to be left the way it is, really.

I will have a look at improving the readme, though.

**Comment by levitating** [comment]
Well if you look a the logic used by Laravel itself, if debug is off you see a general error. No details but the error is clean.

The html file i posted above is not clean, it shows place holders for errors, and developers do not necessarily realize that it is the equivalent of Laravel's "clean error page" meant for the end users. I see what you are saying, but I believe that page can be improved, when there are no specific errors to be shown, a general error should be displayed instead of the place holders.

**Comment by anlutro** [comment]
The reason you're getting placeholders is that you're missing translations for your locale. If you switch to `'en'` the placeholders should be replaced, you can also add your own as documented [here](https://github.com/anlutro/laravel-4-smart-errors#addingcustomizing-localization-strings).

**Comment by levitating** [comment]
Ah I didn't realize this about locale.

In this case I agree with you. Would it be possible to fallback to EN when translation is missing?

**Comment by anlutro** [comment]
I haven't used it myself, but http://laravel.com/docs/4.2/localization describes a "fallback language" config. Maybe that does the job?

**Comment by levitating** [comment]
Yes that's it

**Comment by anlutro** [comment]
I've expanded the readme a bit, specifically [here](https://github.com/anlutro/laravel-4-smart-errors#end-user-responses).
