### ISSUE TITLE
Session data, user agents, and CCs.

### ISSUE THREAD

**Issue by 501st-alpha1** [anlutro/laravel-4-smart-errors#26]
I have a couple Laravel 4 projects that implement similar functionality as this package, so I'm looking into switching to this package to make things easier to maintain.

There are three pieces of functionality that are implemented in those projects that this package does not provide:

* Including a dump of the session, by taking `Session::all()` and then `unset`ing any sensitive data.
* Including the user agent of the client that triggered the error.
* Sending the error notifications to an additional email address as a CC.

Would you be open to adding these items? If so, I can probably submit PRs for all three (though I may have questions about how best to implement them).

**Comment by anlutro** [comment]
I think all of those points seem sensible.

**Comment by anlutro** [comment]
I'm not sure how you would determine sensitive session data, though. With
input I took the naive method of just checking if the string "password" was
in the input data array key, I don't think guessing sensitive session data
is as easy.

**Comment by 501st-alpha1** [comment]
Cool, I'll get started on some PRs. My idea was to add another config option so that the user may define an array of keys that they want wiped.

**Comment by anlutro** [comment]
Sounds good.

**Comment by anlutro** [comment]
Should be completed in https://github.com/anlutro/laravel-4-smart-errors/commit/089deb403c7680ace0ddd883111f557549866c18 - @501st-alpha1 do you want to change your version requirement to dev-master and test it for a bit?

The changes will be released as 2.5.0 when I'm confident everything works as it's supposed to.

**Comment by 501st-alpha1** [comment]
I have this running in production for one of the projects. Just got the first notification in, and it seems to be working fine.

**Comment by 501st-alpha1** [comment]
I've gotten some more errors in over the past few days. I have verified that the session wiping works as expected, and the user agent is included in the email.

**Comment by anlutro** [comment]
Awesome - I'm out traveling so it may be a few days until I can tag a
release.

**Comment by 501st-alpha1** [comment]
No prob.

**Comment by anlutro** [comment]
Completely forgot about this! I just tagged `2.5.0`.
