### ISSUE TITLE
Modified mailer configuration

### ISSUE THREAD

**Issue by realtarget** [anlutro/laravel-4-smart-errors#32]
Hi, 
is it possible to include a modified mailer configuration e.g.
Config::set('services.mandrill.secret', '123456');
in the config.php?
Regards,
Rene

**Comment by anlutro** [comment]
The package just uses the global mailer service, so as long as you've configured that correctly with your mandrill secret or whatever, you shouldn't need to specify anything like that in the package config.

**Comment by realtarget** [comment]
Thanks for the quick reply. The problem is, that we get lots of errors and need to split the error mails in our mandrill statistics by using another smtp login just for your plugin.

**Comment by anlutro** [comment]
I see... I think the easiest way would be to subclass `AlertLogMailer`, call `Config::set` there, then use `App::bind` to replace the package's version of the mailer class with your subclass one.

Though if you're getting to a point where this is a problem for you, may I recommend stop using my package and use something more sophisticated like Sentry instead? :)
